name: katana_localization_annotation
description: Define annotations to use the Katana localization builder. Build with katana_localization_builder using this annotation.
version: 2.2.7
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/katana_localization_annotation

environment:
  sdk: ">=3.5.0-0.0-dev <4.0.0"

dependencies:
  katana: ^2.14.0
dev_dependencies:
  test: ^1.24.0
  katana_test: ^2.1.0
  flutter_lints: ^3.0.0
  import_sorter: ^4.6.0
