name: katana_theme
description: Base package for providing simple and straightforward theme definitions on Flutter.
version: 2.6.0
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/katana_theme

environment:
  sdk: ">=3.5.0-0.0-dev <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  meta:
  katana: ^2.14.0
  katana_theme_annotation: ^2.2.4
  path_provider: ^2.1.3
  flutter_svg: ^2.0.9
dev_dependencies:
  test: ^1.24.0
  katana_test: ^2.1.0
  flutter_lints: ^3.0.0
  import_sorter: ^4.6.0
  
