name: katana_listenables_builder
description: Building system for katana listenables packages. Create a ChangeNotifier that automatically groups multiple Listenables together.
version: 2.1.7
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/katana_listenables_builder

environment:
  sdk: ">=3.5.0-0.0-dev <4.0.0"

dependencies: 
  katana: ^2.14.0
  katana_builder: ^2.1.7
  katana_listenables_annotation: ^2.1.6
  build: ^2.3.0
  dart_style: ^2.2.3
  code_builder: ^4.2.0
  source_gen: ^1.2.2
  analyzer: ^6.0.0

dev_dependencies:
  test: ^1.24.0
  katana_test: ^2.1.0
  flutter_lints: ^3.0.0
  import_sorter: ^4.6.0
