name: masamune_location_google
description: Masamune plugin library for displaying GoogleMap including location information.
version: 2.5.2
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/masamune_location_google

environment:
  sdk: ">=3.5.0-0.0-dev <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  katana: ^2.14.0
  masamune: ^2.13.30
  masamune_location: ^2.4.2
  google_maps_flutter: ^2.6.1
  flutter_polyline_points: ^2.0.0

dev_dependencies:
  test: ^1.24.0
  katana_test: ^2.1.0
  flutter_lints: ^3.0.0
  import_sorter: ^4.6.0

