name: masamune
description: An application development framework centered on automatic code generation using build_runner.
version: 2.13.30
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/masamune

environment:
  sdk: ">=3.5.0-0.0-dev <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  meta: ^1.8.0

  katana: ^2.14.0
  katana_logger: ^2.2.6
  katana_shorten: ^2.1.6
  katana_indicator: ^2.2.4
  katana_scoped: ^2.5.12
  katana_model: ^2.26.15
  katana_model_local: ^2.13.26
  katana_listenables: ^2.2.6
  katana_router: ^2.2.13
  katana_theme: ^2.6.0
  katana_localization: ^2.3.8
  katana_form: ^2.12.17
  katana_auth: ^2.9.0
  katana_ui: ^2.9.0
  katana_prefs: ^2.2.6
  katana_storage: ^2.2.7
  katana_functions: ^2.6.6
  masamune_annotation: ^2.6.9
dev_dependencies:
  test: ^1.24.0
  katana_test: ^2.1.0
  flutter_lints: ^3.0.0
  import_sorter: ^4.6.0
  