name: masamune_location_background
description: Masamune plugin library for handling background location information in apps.
version: 2.4.75
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/masamune_location_background

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  katana: ^2.14.0
  masamune: ^2.13.30
  background_locator_2: ^2.0.0
  path_provider: ^2.1.3
  permission_handler: ^11.0.0
  masamune_location_platform_interface: ^2.4.2
  universal_platform: ^1.0.0+1
  shared_preferences: ^2.2.2

dev_dependencies:
  test: ^1.24.0
  katana_test: ^2.1.0
  flutter_lints: ^3.0.0
  import_sorter: ^4.6.0

