name: katana_scoped
description: A state management package to allow for retention and management while specifying the scope of the state.
version: 2.5.12
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/katana_scoped

environment:
  sdk: ">=3.5.0-0.0-dev <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  katana: ^2.14.0
  katana_logger: ^2.2.6
dev_dependencies:
  flutter_test:
    sdk: flutter

  test: ^1.24.0
  katana_test: ^2.1.0
  flutter_lints: ^3.0.0
  import_sorter: ^4.6.0
