name: masamune_location
description: Masamune plugin library for handling location information in apps.
version: 2.4.2
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/masamune_location

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  katana: ^2.14.0
  masamune: ^2.13.30
  flutter_compass: ^0.7.0
  masamune_location_platform_interface: ^2.4.2
  location: ^5.0.3
  permission_handler: ^11.1.0

dev_dependencies:
  test: ^1.24.0
  katana_test: ^2.1.0
  flutter_lints: ^3.0.0
  import_sorter: ^4.6.0

