name: masamune_agora
description: Plug-in for Masamune framework to use Agora.io. Includes support for recording.
version: 2.4.75
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/masamune_agora

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  katana: ^2.14.0
  masamune: ^2.13.30
  agora_rtc_engine: ^6.3.0
  permission_handler: ^11.0.0
  universal_platform: ^1.0.0+1
dev_dependencies:
  test: ^1.24.0
  katana_test: ^2.1.0
  flutter_lints: ^3.0.0
  import_sorter: ^4.6.0
