name: katana_router
description: A package to automatically create routing configurations with build_runner to enable type-safe routing.
version: 2.2.13
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/katana_router

environment:
  sdk: ">=3.5.0-0.0-dev <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  katana: ^2.14.0
  katana_logger: ^2.2.6
  katana_router_annotation: ^2.1.7

dev_dependencies:
  test: ^1.24.0
  katana_test: ^2.1.0
  flutter_lints: ^3.0.0
  import_sorter: ^4.6.0
