name: masamune_universal_ui
description: The package provide a universal UI that aims to be written in one code on any platform.
version: 2.4.10
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune/tree/master/packages/masamune_universal_ui

environment:
  sdk: ">=3.5.0-0.0-dev <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  katana: ^2.14.0
  masamune: ^2.13.30
  universal_platform: ^1.0.0+1
  url_launcher: ^6.2.6
  visibility_detector: ^0.4.0+2
dev_dependencies:
  test: ^1.24.0
  katana_test: ^2.1.0
  flutter_lints: ^3.0.0
  import_sorter: ^4.6.0
